# Generated by Django 3.0.3 on 2020-07-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0003_auto_20200701_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
    ]
