# Generated by Django 3.0.3 on 2020-07-02 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0004_collected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collected',
            old_name='tag',
            new_name='fl_Name',
        ),
        migrations.RenameField(
            model_name='collected',
            old_name='Name',
            new_name='u_Name',
        ),
    ]
